<a href="https://colab.research.google.com/github/Varshini151205/ML/blob/main/MLpractice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
n=np.arange(10)
print(n)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
n2=(n[n%2==0])
print(n2)

[0 2 4 6 8]


In [ ]:
n1=np.arange(10).reshape(2,5)
print(n1)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
print(np.trace(n1))

6


In [ ]:
n1=np.arange(12).reshape(3,4)
print(np.vstack(n))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
n=np.eye(3,3)
print(n)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
n=np.arange(10)
n1=np.arange(4,9)
print(np.intersect1d(n,n1))


[4 5 6 7 8]


In [ ]:
import pandas as pd
import numpy as np
import string
EngAlph = pd.Series(list(string.ascii_lowercase))
print( " EngAlph: /n", EngAlph)

 EngAlph: /n 0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object


In [ ]:
Vowels = pd.Series([0, 0, 0, 0, 0], index=['a', 'e', 'i', 'o', 'u'])
print("\n Vowels:\n", Vowels)
print("Is Vowels empty? ", Vowels.empty)


 Vowels:
 a    0
e    0
i    0
o    0
u    0
dtype: int64
Is Vowels empty?  False


In [ ]:
friends_dict = {'varshini': 318, 'anushka': 320, 'rasagna': 151, 'rida': 161, 'harshitha': 146}
Friends = pd.Series(friends_dict)
print("\n Friends:\n", Friends)


 Friends:
 varshini     318
anushka      320
rasagna      151
rida         161
harshitha    146
dtype: int64


In [ ]:
MTseries = pd.Series(dtype='float64')
print("\n MTseries:\n", MTseries)
print("Is MTseries empty? ", MTseries.empty)


 MTseries:
 Series([], dtype: float64)
Is MTseries empty?  True


In [ ]:
days_array = np.array([31,28,31,30,31,30,31,31,30,31,30,31])
MonthDays = pd.Series(days_array, index=range(1,13))
print("\nMonthDays:\n", MonthDays)


MonthDays:
 1     31
2     28
3     31
4     30
5     31
6     30
7     31
8     31
9     30
10    31
11    30
12    31
dtype: int64


In [ ]:
Vowels[:] = 10
print("\nVowels set to 10:\n", Vowels)


Vowels set to 10:
 a    10
e    10
i    10
o    10
u    10
dtype: int64


In [ ]:
Vowels = Vowels / 2
print("\nVowels divided by 2:\n", Vowels)


Vowels divided by 2:
 a    5.0
e    5.0
i    5.0
o    5.0
u    5.0
dtype: float64


In [ ]:
Vowels1 = pd.Series([2, 5, 6, 3, 8], index=['a', 'e', 'i', 'o', 'u'])
print("\nVowels1:\n", Vowels1)


Vowels1:
 a    2
e    5
i    6
o    3
u    8
dtype: int64


In [ ]:
Vowels3 = Vowels + Vowels1
print("\n Vowels3 (Vowels + Vowels1):\n", Vowels3)


 Vowels3 (Vowels + Vowels1):
 a     7.0
e    10.0
i    11.0
o     8.0
u    13.0
dtype: float64


In [ ]:
print("\n Vowels1 - Vowels:\n", Vowels1 - Vowels)
print("  Vowels1 * Vowels:\n", Vowels1 * Vowels)
print("  Vowels1 / Vowels:\n", Vowels1 / Vowels)


 Vowels1 - Vowels:
 a   -3.0
e    0.0
i    1.0
o   -2.0
u    3.0
dtype: float64
  Vowels1 * Vowels:
 a    10.0
e    25.0
i    30.0
o    15.0
u    40.0
dtype: float64
  Vowels1 / Vowels:
 a    0.4
e    1.0
i    1.2
o    0.6
u    1.6
dtype: float64


In [ ]:
Vowels1.index = ['A', 'E', 'I', 'O', 'U']
print("\nVowels1 with new labels:\n", Vowels1)


Vowels1 with new labels:
 A    2
E    5
I    6
O    3
U    8
dtype: int64


In [ ]:
print("Properties:")
print("EngAlph - Dim:", EngAlph.ndim, ", Size:", EngAlph.size, ", Values:", EngAlph.values)
print("Vowels - Dim:", Vowels.ndim, ", Size:", Vowels.size, ", Values:", Vowels.values)
print("Friends - Dim:", Friends.ndim, ", Size:", Friends.size, ", Values:", Friends.values)
print("MTseries - Dim:", MTseries.ndim, ", Size:", MTseries.size, ", Values:", MTseries.values)
print("MonthDays - Dim:", MonthDays.ndim, ", Size:", MonthDays.size, ", Values:", MonthDays.values)

Properties:
EngAlph - Dim: 1 , Size: 26 , Values: ['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l' 'm' 'n' 'o' 'p' 'q' 'r'
 's' 't' 'u' 'v' 'w' 'x' 'y' 'z']
Vowels - Dim: 1 , Size: 5 , Values: [5. 5. 5. 5. 5.]
Friends - Dim: 1 , Size: 5 , Values: [318 320 151 161 146]
MTseries - Dim: 1 , Size: 0 , Values: []
MonthDays - Dim: 1 , Size: 12 , Values: [31 28 31 30 31 30 31 31 30 31 30 31]


In [ ]:
SeriesEmpty = MTseries.rename("SeriesEmpty")
print("\nRenamed MTseries:\n", SeriesEmpty)


Renamed MTseries:
 Series([], Name: SeriesEmpty, dtype: float64)


In [ ]:
MonthDays.index.name = 'monthno'
Friends.index.name = 'Fname'
print("\nMonthDays with index name:\n", MonthDays)
print("Friends with index name:\n", Friends)


MonthDays with index name:
 monthno
1     31
2     28
3     31
4     30
5     31
6     30
7     31
8     31
9     30
10    31
11    30
12    31
dtype: int64
Friends with index name:
 Fname
varshini     318
anushka      320
rasagna      151
rida         161
harshitha    146
dtype: int64


In [ ]:
print("3rd and 2nd value from Friends:\n", Friends.iloc[[2, 1]])


3rd and 2nd value from Friends:
 Fname
rasagna    151
anushka    320
dtype: int64


In [ ]:
print("Alphabets from 'e' to 'p':\n", EngAlph[4:16])


Alphabets from 'e' to 'p':
 4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
dtype: object


In [ ]:
print("Last 10 values:\n", EngAlph.tail(10))


Last 10 values:
 16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
dtype: object


In [ ]:
print("MTseries:\n", MTseries)


MTseries:
 Series([], dtype: float64)


In [ ]:
print(" Months 3 to 7:\n", MonthDays.loc[3:7])


 Months 3 to 7:
 monthno
3    31
4    30
5    31
6    30
7    31
dtype: int64


In [ ]:
print("MonthDays in reverse:\n", MonthDays[::-1])


MonthDays in reverse:
 monthno
12    31
11    30
10    31
9     30
8     31
7     31
6     30
5     31
4     30
3     31
2     28
1     31
dtype: int64


In [ ]:
import pandas as pd

data = {
    '2014': [100.5, 150.8, 200.9, 30000, 40000],
    '2015': [12000, 18000, 22000, 30000, 45000],
    '2016': [20000, 50000, 70000, 100000, 125000],
    '2017': [50000, 60000, 70000, 80000, 90000]
}

index_labels = ['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti']

Sales = pd.DataFrame(data, index=index_labels)
print("Sales DataFrame:\n", Sales)


Sales DataFrame:
             2014   2015    2016   2017
Madhu      100.5  12000   20000  50000
Kusum      150.8  18000   50000  60000
Kinshuk    200.9  22000   70000  70000
Ankit    30000.0  30000  100000  80000
Shruti   40000.0  45000  125000  90000


In [ ]:
print("Row labels:\n", Sales.index)


Row labels:
 Index(['Madhu', 'Kusum', 'Kinshuk', 'Ankit', 'Shruti'], dtype='object')


In [ ]:
print("Column labels:\n", Sales.columns)


Column labels:
 Index(['2014', '2015', '2016', '2017'], dtype='object')


In [ ]:
print("Data types:\n", Sales.dtypes)


Data types:
 2014    float64
2015      int64
2016      int64
2017      int64
dtype: object


In [ ]:
print("Dimensions:", Sales.ndim)
print("Shape:", Sales.shape)
print("Size:", Sales.size)
print("Values:\n", Sales.values)


Dimensions: 2
Shape: (5, 4)
Size: 20
Values:
 [[1.005e+02 1.200e+04 2.000e+04 5.000e+04]
 [1.508e+02 1.800e+04 5.000e+04 6.000e+04]
 [2.009e+02 2.200e+04 7.000e+04 7.000e+04]
 [3.000e+04 3.000e+04 1.000e+05 8.000e+04]
 [4.000e+04 4.500e+04 1.250e+05 9.000e+04]]


In [ ]:
print("Last 2 rows:\n", Sales.tail(2))


Last 2 rows:
            2014   2015    2016   2017
Ankit   30000.0  30000  100000  80000
Shruti  40000.0  45000  125000  90000


In [ ]:
print("First 2 columns:\n", Sales.iloc[:, 0:2])


First 2 columns:
             2014   2015
Madhu      100.5  12000
Kusum      150.8  18000
Kinshuk    200.9  22000
Ankit    30000.0  30000
Shruti   40000.0  45000


In [ ]:
sales2_data = {
    '2018': {
        'Madhu': 160000,
        'Kusum': 110000,
        'Kinshuk': 500000,
        'Ankit': 340000,
        'Shruti': 900000
    }
}

Sales2 = pd.DataFrame(sales2_data)
print("Sales2 DataFrame:\n", Sales2)


Sales2 DataFrame:
            2018
Madhu    160000
Kusum    110000
Kinshuk  500000
Ankit    340000
Shruti   900000


In [ ]:
print("Is Sales2 empty?:", Sales2.empty)


Is Sales2 empty?: False


In [ ]:
Sales = pd.concat([Sales, Sales2], axis=1)
print("Appended Sales2 to Sales:\n", Sales)


Appended Sales2 to Sales:
             2014   2015    2016   2017    2018
Madhu      100.5  12000   20000  50000  160000
Kusum      150.8  18000   50000  60000  110000
Kinshuk    200.9  22000   70000  70000  500000
Ankit    30000.0  30000  100000  80000  340000
Shruti   40000.0  45000  125000  90000  900000


In [ ]:
Sales = Sales.T
print("Transposed Sales:\n", Sales)


Transposed Sales:
          Madhu     Kusum   Kinshuk     Ankit    Shruti
2014     100.5     150.8     200.9   30000.0   40000.0
2015   12000.0   18000.0   22000.0   30000.0   45000.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0


In [ ]:
print("Sales in 2017:\n", Sales.loc['2017'])


Sales in 2017:
 Madhu      50000.0
Kusum      60000.0
Kinshuk    70000.0
Ankit      80000.0
Shruti     90000.0
Name: 2017, dtype: float64


In [ ]:
print("Madhu and Ankit in 2017 & 2018:\n", Sales.loc[['2017', '2018'], ['Madhu', 'Ankit']])


Madhu and Ankit in 2017 & 2018:
          Madhu     Ankit
2017   50000.0   80000.0
2018  160000.0  340000.0


In [ ]:
print("Shruti in 2016:\n", Sales.loc['2016', 'Shruti'])


Shruti in 2016:
 125000.0


In [ ]:
Sales['Sumeet'] = [196.2, 37800, 52000, 78438, 38852]
print("Added Sumeet:\n", Sales)


Added Sumeet:
          Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2014     100.5     150.8     200.9   30000.0   40000.0    196.2
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0  38852.0


In [ ]:
Sales = Sales.drop(index='2014')
print(" Deleted 2014:\n", Sales)


 Deleted 2014:
          Madhu     Kusum   Kinshuk     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   22000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0   70000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   70000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  500000.0  340000.0  900000.0  38852.0


In [ ]:
Sales = Sales.drop(columns='Kinshuk')
print("Deleted Kinshuk:\n", Sales)


Deleted Kinshuk:
          Madhu     Kusum     Ankit    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
Sales = Sales.rename(columns={'Ankit': 'Vivaan', 'Madhu': 'Shailesh'})
print("Renamed Ankit & Madhu:\n", Sales)


Renamed Ankit & Madhu:
       Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  160000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
Sales.at['2018', 'Shailesh'] = 100000
print(" Updated Shailesh 2018 sale:\n", Sales)


 Updated Shailesh 2018 sale:
       Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  100000.0  110000.0  340000.0  900000.0  38852.0


In [ ]:
Sales.to_csv('SalesFigures.csv', index=False, header=False)
print("Written to SalesFigures.csv without labels")


Written to SalesFigures.csv without labels


In [ ]:
SalesRetrieved = pd.read_csv('SalesFigures.csv', header=None)
SalesRetrieved.index = Sales.index
SalesRetrieved.columns = Sales.columns
print("SalesRetrieved with labels:\n", SalesRetrieved)


SalesRetrieved with labels:
       Shailesh     Kusum    Vivaan    Shruti   Sumeet
2015   12000.0   18000.0   30000.0   45000.0  37800.0
2016   20000.0   50000.0  100000.0  125000.0  52000.0
2017   50000.0   60000.0   80000.0   90000.0  78438.0
2018  100000.0  110000.0  340000.0  900000.0  38852.0
